## 練習時間
假設我們資料中類別的數量並不均衡，在評估準確率時可能會有所偏頗，試著切分出 y_test 中，0 類別與 1 類別的數量是一樣的 (亦即 y_test 的類別是均衡的)

In [1]:
import numpy as np
X = np.arange(1000).reshape(200, 5)
y = np.zeros(200)
y[:40] = 1

In [2]:
y

array([ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0

可以看見 y 類別中，有 160 個 類別 0，40 個 類別 1 ，請試著使用 train_test_split 函數，切分出 y_test 中能各有 10 筆類別 0 與 10 筆類別 1 。(HINT: 參考函數中的 test_size，可針對不同類別各自作切分後再合併)

In [3]:
from sklearn.model_selection import train_test_split

In [4]:
X_0 = X[np.where(y==0)]
y_0 = y[np.where(y==0)]
X_1 = X[np.where(y==1)]
y_1 = y[np.where(y==1)]

In [5]:
X_0_train, X_0_test, y_0_train, y_0_test = train_test_split(X_0,y_0,test_size=(10/y_0.size))
X_1_train, X_1_test, y_1_train, y_1_test = train_test_split(X_1,y_1,test_size=(10/y_1.size))

In [6]:
X_train = np.concatenate((X_0_train,X_1_train),axis=0)
X_test  = np.concatenate((X_0_test,X_1_test),axis=0)
y_train = np.concatenate((y_0_train,y_1_train),axis=0)
y_test  = np.concatenate((y_0_test,y_1_test),axis=0)

In [7]:
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(180, 5)
(20, 5)
(180,)
(20,)


In [8]:
print("X_test: \n", X_test)
print("y_test: \n", y_test)

X_test: 
 [[245 246 247 248 249]
 [275 276 277 278 279]
 [965 966 967 968 969]
 [510 511 512 513 514]
 [565 566 567 568 569]
 [800 801 802 803 804]
 [855 856 857 858 859]
 [960 961 962 963 964]
 [455 456 457 458 459]
 [305 306 307 308 309]
 [ 35  36  37  38  39]
 [115 116 117 118 119]
 [125 126 127 128 129]
 [ 50  51  52  53  54]
 [ 10  11  12  13  14]
 [145 146 147 148 149]
 [160 161 162 163 164]
 [  5   6   7   8   9]
 [ 15  16  17  18  19]
 [180 181 182 183 184]]
y_test: 
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  1.  1.  1.  1.  1.  1.  1.  1.
  1.  1.]
